version = 1

exclude_patterns = [
  "3rdparty/**",
  "**/node_modules/**",
  "dist/**",
  "build/**",
  "**/__pycache__/**",
  ".git/**",
  "docs/**",
  "data/**"
]

[[analyzers]]
name = "python"
dependency_file_paths = [
  "python/pyproject.toml"
]

  [analyzers.meta]
  runtime_version = "3.11"

[[analyzers]]
name = "javascript"
dependency_file_paths = [
  "typescript/package.json"
]

  [analyzers.meta]
  dialect = "typescript"
  module_system = "es-modules"
